### ISSUE TITLE
cookie

### ISSUE THREAD

**Issue by insoxin** [metowolf/script#10]
http://data.bilibili.com/v/flashplay/live_player?guid=*&buffertimes=&loadtime=*&fid=LivePlayerExPlus&delta%5Fts=&fver=6
🌚按你博客的，没找到那个都是这类的

**Comment by metowolf** [comment]
新版的似乎修改了一些参数，只需要找 `data.bilibili.com`、`api.live.bilibili.com` 的 cookie 即可
