### ISSUE TITLE
网易云脚本执行后提示出错

### ISSUE THREAD

**Issue by EdisonJwa** [metowolf/script#11]
PHP Fatal error:  Uncaught Error: Call to undefined function Metowolf\curl_init() in /root/script/neteasemusic/meting.php:52
Stack trace:
#0 /root/script/neteasemusic/meting.php(545): Metowolf\Meting->curl(Array)
#1 /root/script/neteasemusic/run.php(10): Metowolf\Meting->playlist(34436881)
#2 {main}
  thrown in /root/script/neteasemusic/meting.php on line 52

**Comment by metowolf** [comment]
这是因为缺少 curl 和 php-curl 拓展，可以自查一下 phpinfo();
