### ISSUE TITLE
centos下，neteasemusic出现中文乱码，debian下正常

### ISSUE THREAD

**Issue by NorthNanmu** [metowolf/script#12]
不晓得是curl的header问题还是系统的问题

这是`centos`的主机（国内）

![pqqjrjvd qltzo euf76t](https://user-images.githubusercontent.com/28924440/39106897-24fa81a6-46f1-11e8-92e4-43ba09b7421a.png)

这是`debian`的主机（海外）

![3495mlp kms 76t jt1gp b](https://user-images.githubusercontent.com/28924440/39106984-aa49e266-46f1-11e8-90e3-95768777682a.png)

**Comment by metowolf** [comment]
这就比较诡异了，我是直接执行 wget 来写入的

**Comment by NorthNanmu** [comment]
确认并非代码原因，原因是我使用的`winscp`这个软件需要在连接服务器时勾选`文件名UTF-8编码`
参考链接：https://blog.csdn.net/rchm8519/article/details/48351843
