### ISSUE TITLE
这是标题啦啦啦啦啦

### ISSUE THREAD

**Issue by ec-to** [metowolf/script#6]
撸撸，可不可以考虑加入一个状态码返回咧。
每次运行时判断cookie失效，然后返回一个http状态码。
可以便利于，监控平台设置报警项目，当cookie失效后便于知晓。
![image](https://cloud.githubusercontent.com/assets/24844835/23936781/ea177864-098e-11e7-9128-9ad1de84d09b.png)

**Comment by rhjdvsgsgks** [comment]
同意
